#define CONFIGURATION_SETDEFAULT_CONFIRM	"모든 툴바의 설정을 기본 값으로 복원 하시겠습니까?"
#define LOGIN_INCORRECT_ALERT				"아이디 또는 패스워드를 확인해 주세요."
#define LOGIN_CORRECT_ALERT					"로그인이 성공하였습니다."
#define LOGOUT_CORRECT_ALERT				"로그아웃 되었습니다."
#define LOGOUT_INCORRECT_ALERT				"로그아웃이 실패하였습니다."
#define LOING_EMPTYID_ALERT					"아이디를 입력해 주세요"
#define LOING_EMPTYPASSWORD_ALERT			"패스워드를 입력해 주세요"

#define LOGIN_STATE_LOGOUT					"로그아웃(&O)"
#define LOGIN_STATE_LOGIN					"로그인(&L)"
#define LOGIN_INFO_MESSAGE					"'%s'님은 현재 로그인 상태입니다.\n\n로그아웃 하시겠습니까?"
#define LOGIN_CONFIRM_MESSAGE				"선택하신 서비스는 회원에게만 제공됩니다. \n\n지금 로그인 하시겠습니까?"
#define MANAGERDLG_CLIPBOARD_COMPLETE		"클립보드로 복사 되었습니다."
#define MANAGERDLG_SAVEFILE_COMPLETE		"파일로 저장 되었습니다."

#define MSG_PREPAREWORK						"작업 준비중"
#define MSG_PREPAREPARSE					"파싱 준비중"
#define MSG_PREPAREWORKPARSE				"테그 파싱 작업 준비중"
#define MSG_COMPLETEWORKPARSE				"테그 파싱 작업 완료"
#define MSG_PREPAREHTTPCONNECT				"서버 연결중"
#define MSG_COMPLETEEND						"완료 "
#define MSG_COMPLETEFILUREWORK				"전송 실패: "
#define MSG_COMPLETESUCCESSWORK				"전송 완료"